name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
      - name: Install racket and raco
        run: sudo apt-get install racket -y
      - name: clone repo
        run: git clone https://github.com/valtyr/forritunarmal.git
      - name: Test code
        run: raco test forritunarmal
 
